### ISSUE TITLE
No .exe

### ISSUE THREAD

**Issue by Rynerak** [NiyaShy/XB1ControllerBatteryIndicator#1]
Microsoft Xbox One Controller Play and Charge Kit - SKU S3V-00015 (2018 Model)
Microsoft Xbox Elite Wireless Controller - HM3-00001
Microsoft Xbox Wireless Adapter for Windows 10 - 6HN-00006

Tray Icon indicator is a question mark on a battery.

**Comment by NiyaShy** [comment]
So I take it the controller and wireless dongle are properly set up and recognized by windows and games, right? 
Which of the 2 possible "?" icons is shown, the "standard" one with just the ? or the one with a tiny number over the controller part (see the wiki page for reference images).

The "standard" icon would imply that the controller isn't recognized at all, and that would be rather odd.
The only case that I've heard of so far was that display was stuck on the icon with the controller number for a longer time (when you hover over the icon it should show a message that no battery level was detected yet). But that should fix itself after you've used the controller for a bit.

What version of Win10 (1709, 1703) are you running? Are you using the latest version (1.2.0) of the tool?

Please provide a bit more info about what's wrong.

**Comment by NiyaShy** [comment]
No response for 2 weeks, so I take it you either fixed it yourself or don't want to help with further details. Closing your issue.
