### ISSUE TITLE
Controller activated popup

### ISSUE THREAD

**Issue by Akensai** [NiyaShy/XB1ControllerBatteryIndicator#10]
Hi there,

Think it would be possible to do a simple xinput event to show a popup? Sure it would only work if a game isn't full screen. But the goal being to hold a button to get a quick indicator.

A couple years ago I had written something like that for Rainmeter using an xinput.dll someone else created, it was incredibly simple. Unfortunately I lost it and Windows10 kinda changed how all that works.

I still think it should be possible in C++ form. Just a suggestion.

Cheers

**Comment by NiyaShy** [comment]
Hey,
what exactly do you mean? That holding a button gives you a "battery level is at X" message?
It should be possible, but there is one thing: which button to map it to. Depending on what you're playing long presses for the "normal" buttons could happen at any time, and I'd have to look into if it's possible to map something to the XB button.

**Comment by Akensai** [comment]
Ages ago the old Xbox 360 controllers had the function built into the Xbox
button (long press). Now that opens up the game bar so that cant be used.

Maybe start+select long press?

Anyway, it's just a thought. I was planning on starting a project something
like you have and never got around to it, then found yours.
As per mapping + popup, lot of games at DX10+ wont allow a popup to even
show so it may be a wasted effort. Would have to be playing
windowed/borderless for any use.

Cheers

**Comment by lgvaioli** [comment]
> Ages ago the old Xbox 360 controllers had the function built into the Xbox button (long press). Now that opens up the game bar so that cant be used.

I just wanted to clarify that this is not entirely correct. You can easily disable the opening of the game bar when you press the Xbox button by unchecking "Open Game bar using this button on a controller: [Xbox button image]" in Settings/Gaming in Windows 10.

>As per mapping + popup, lot of games at DX10+ wont allow a popup to even
show so it may be a wasted effort. Would have to be playing
windowed/borderless for any use.

This is the main difficulty I see in implementing this feature. For this feature to be as "universal" as possible, some kind of overlay solution (à la Fraps/Steam) would have to be implemented, but I have no idea how difficult that would be. I also feel that this feature wouldn't be too useful in the current implementation, as the battery levels indicated by XInput are incredibly vague (full, medium, low, empty).

**Comment by NiyaShy** [comment]
Igvaioli summarized it pretty well, this would be hard to implement and usefulness would be... very situational. As such, I'll take the liberty of closing this issue.
