### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by SlayerMR** [NiyaShy/XB1ControllerBatteryIndicator#17]
Hello, I was interested in the project and the program is being useful for me. An improvement that I would appreciate would be a way of being able to place icons on the internet. In the code I was able to find the folder with the images and thought that if I replaced with other icons it would work, but I am not aware of programming to transform the code with the new images into an execution program. Can you tell me if there is such a possibility? Changing the subject, if it is of your interest I would like to be useful translating your program into Brazilian Portuguese, I am from Brazil and I believe that your program will be very useful for users of control xbox one s by bluetooth.

**Comment by NiyaShy** [comment]
Hey, great to hear that you like it.
Changing the icons for yourself shouldn't be too hard to do. You will need Visual Studio for it, the current version (2017 community edition) can be downloaded for free from Microsoft.

Download the source code package of the program and open the code in Visual Studio via the .snl file. When you've done that you can simply replace the .ico files within the Resources folder with your own version (just make sure that you keep the file names, and of course your versions also have to be .ico files.

Once you have the icons in there, you can build the executable program with Visual Studio.

And about translations, it's already on my list of things to implement (see issue #3 ), but I don't have a schedule for when I will find the time to do so.

**Comment by SlayerMR** [comment]
![Print](https://user-images.githubusercontent.com/48873552/54881833-f8bd5600-4e32-11e9-837e-5ad9c8f5eb3f.png)

Hey, thanks for your response.
I downloaded de Visual Studio and I changed the original icons to the ones I wanted, but, when I try to build the executable program, an error shows up and it says: "The program couldn't find the manifest's authentification certificate in the certificate storage." (screenshot above)
Can you guide me on how to build this executable program on Visual Studio?

I'm looking forward to hear from you.
Thank you.

**Comment by NiyaShy** [comment]
Hey,
I think I know where this is coming from. 
Go to Project -> Properties (at the bottom of the menu), and then to "Signing" (4th option from the bottom). If the "Sign the ClickOnce manifests" box is checked, uncheck it.

I already disabled code signing on the testing branch (basically a copy of the code that I can work on without screwing up the main code), but since you downloaded the code from the "master" branch that I haven't updated with that change yet, you got that error.

**Comment by SlayerMR** [comment]
Thanks for listening. After following your instructions I was able to create the EXE file. It took a few hours until I could create an icon that looked aesthetically beautiful, but I did! Thank you again!

**Comment by NiyaShy** [comment]
You're welcome, enjoy your new custom icon(s) 😉
