### ISSUE TITLE
1.2.0 runs normally, 1.2.1 flashes after running

### ISSUE THREAD

**Issue by aylz10** [NiyaShy/XB1ControllerBatteryIndicator#22]
1.2.0 runs normally, 1.2.1 flashes after running
Windows 7 x64 with ".NET Framework 4.7.2 installed on Windows 7"
After checking the event viewer, there are 3 exception errors.
no.1
错误存储段 ，类型 0
事件名称: CLR20r3
响应: 不可用
Cab ID: 0

问题签名: 
P1: XB1ControllerBatteryIndicator
P2: 1.2.1.0
P3: 5bf1c15d
P4: mscorlib
P5: 4.7.3133.0
P6: 5b57c26c
P7: 3bd3
P8: 14
P9: System.TypeLoadException
P10: 

附加文件: 

可在此处获取这些文件: 
C:\Users\aylz\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_XB1ControllerBat_39e6d381d2cbe4ddbb52b14d2443953f33ab64e_33fcf119

分析符号: 
重新检查解决方案: 0
报告 Id: dd263c9e-5d55-11e9-9567-005056c00008
报告状态: 4
no.2
错误应用程序名称: XB1ControllerBatteryIndicator.exe，版本: 1.2.1.0，时间戳: 0x5bf1c15d
错误模块名称: KERNELBASE.dll，版本: 6.1.7601.24260，时间戳: 0x5b946d85
异常代码: 0xe0434352
错误偏移量: 0x0000c54f
错误进程 ID: 0x2ab0
错误应用程序启动时间: 0x01d4f1629ef8141f
错误应用程序路径: D:\xb1\XB1ControllerBatteryIndicator.exe
错误模块路径: C:\windows\syswow64\KERNELBASE.dll
报告 ID: dd263c9e-5d55-11e9-9567-005056c00008
no.3
应用程序: XB1ControllerBatteryIndicator.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.PlatformNotSupportedException

异常信息: System.TypeLoadException
   在 XB1ControllerBatteryIndicator.SystemTrayViewModel.RefreshControllerState()
   在 System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Threading.ThreadHelper.ThreadStart()

I am very sorry, I am Chinese and my English is very poor. I wrote this issue with google translation.

**Comment by NiyaShy** [comment]
Hey,
I think error no.3 already says what is wrong: System.PlatformNotSupportedException
I have no windows 7 computers available for testing any more, and with Microsoft ending support for windows 7 in January 2020 I also have no plans for supporting it any longer.
If you can, please update your computer to windows 10. It is free when you have a valid windows 7 license.

**Comment by aylz10** [comment]
Ok, thank you very much.
Temporarily not considering upgrading Windows 10, I continue to use version 1.2.0.
