### ISSUE TITLE
Make toast vanish after a few seconds

### ISSUE THREAD

**Issue by NiyaShy** [NiyaShy/XB1ControllerBatteryIndicator#24]
As asked by @buzzcola107 [here](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/issues/3#issuecomment-485991731):

> And I have a feedback/suggestions:
The other day I was playing GTAV and the warning (toast) appeared in mission over the map ( and I fail the mission lol ). And if i click on the button Shut up!, its minimizes the game (risk of crash in some game).  
I ask if it is possible to just make the warning appear only for a few seconds ( like 7 seconds )

**Comment by NiyaShy** [comment]
I'll see what I can do about that. Was already thinking about adding a way to disable the toast completely if you prefer just audio hints (possible now that the notification sound was added), so it might be possible to add a menu for selecting  

- show toast
  - never
  - for X seconds
  - until dismissed

**Comment by buzzcola107** [comment]
Have 3 choice of toast+ audio on/off will be great.
Just audio, if have loud sound in game like explosive or big, action you mabry not ear the warning., but is always good to have choice.

Good day !

**Comment by jack1142** [comment]
Considering that on other issue you mentioned that people showing interest might convince you, I want to +1 this, it's very annoying for me, when I'm playing Rocket League considering that the location of Windows's toast hides the boost level perfectly and it doesn't auto-hide after few seconds 😄

**Comment by NiyaShy** [comment]
Hey,
this is already on my list of things to implement since I got feedback here and on reddit that there are situations where the toast is disturbing and an option to disable it would be nice. Just haven't had the time to get into this yet.

It's planned for the next (non-language-addition) update, hence the milestone tag 😉 But there's no release schedule of it (yet).

**Comment by NiyaShy** [comment]
So, a lot has happened in the last months, new features were submitted to the testing branch (aka, they aren't in the released main version yet) that affect the notifications. You can now disable the toasts completely, and in addition to the already released notification sound there's a new overlay/popup that shouldn't steal focus from fullscreen games.

The new overhauled context menu:
![image](https://user-images.githubusercontent.com/21028106/104107685-957a0d80-52be-11eb-85be-28f6bcffecb3.png)
The new popup:
![image](https://user-images.githubusercontent.com/21028106/104107703-ac206480-52be-11eb-8988-192e2124c8ce.png)
Configuration dialogue for the popup:
![image](https://user-images.githubusercontent.com/21028106/104107782-657f3a00-52bf-11eb-9b6d-4f36a00668d9.png)

The big question is: would that be enough already, or do you still want an option to hide the toast messages after a while? The big advantage of toasts is that they can stay on screen for more than just a few seconds, so if you just want a quick "hey, battery is getting low" the popup should be more than enough.
