### ISSUE TITLE
I have older version, works flawlessly on pc with 360 stick and wireless adapter for pc

### ISSUE THREAD

**Issue by djmdesign** [NiyaShy/XB1ControllerBatteryIndicator#34]

**Comment by djmdesign** [comment]
works flawless on win10x64 wireless adapter for pc and wireless 360 controller.
thanks a ton

the adpater software doesnt let you use gamebar and have battery status, its one or the other, and opening gamebar to check battery isnt as efficient and effortless as your app.

**Comment by NiyaShy** [comment]
Hey,
I'm not entirely sure if this is meant as just a "thanks, it works" or an actual issue. 
If it's the former, great to hear that you like it. But issues aren't really meant for that, so please close it or let me know so I can close it for you.
If it's the latter, please give a few more details what's wrong.

**Comment by NiyaShy** [comment]
Since you didn't respond I take it the former was the case. Closing it.
