### ISSUE TITLE
I can't compile de solution in Windows 10

### ISSUE THREAD

**Issue by juanmiguel431** [NiyaShy/XB1ControllerBatteryIndicator#36]
The compiler can't find the reference for Windows.Data, Windows.Foundation and Windows.UI.

using Windows.UI.Notifications;
using Windows.Data.Xml.Dom;

![image](https://user-images.githubusercontent.com/10950943/71489343-83d0df80-27fb-11ea-9ecc-96d101e60d2f.png)

Please, how can I fix this?

I have windows 10 Pro. Version 1909.  And Visual Studio 2019.

**Comment by NiyaShy** [comment]
Hey,

that's a "known bug" (or maybe intentional) with Visual Studio 2019, it can't access the folder where previous versions of VS could still find info about those references.

Please check issue #28, a solution was discussed there.
