### ISSUE TITLE
Application don't start

### ISSUE THREAD

**Issue by vladimirpol** [NiyaShy/XB1ControllerBatteryIndicator#47]
Windows 10 was updated up to 2004 and after "XB1ControllerBatteryIndicator" won't start. Can't see it in process list.
XB1ControllerBatteryIndicator v. 1.3.1
I tried to launch it with administrator rights - it didn't help.
Can anyone provide advise? (I downloaded the latest release XB1ControllerBatteryIndicator and unpack it in the same folder, 
overwritten old settings file and executable one | it didn't help too)

**Comment by vladimirpol** [comment]
I checked Event Viewer:
Имя сбойного приложения: XB1ControllerBatteryIndicator.exe, версия: 1.3.1.0, метка времени: 0x5f15ebc7
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.19041.572, метка времени: 0x979ddb1d
Код исключения: 0xe0434352
Смещение ошибки: 0x00129ab2
Идентификатор сбойного процесса: 0x3290
Время запуска сбойного приложения: 0x01d6acf94055318a
Путь сбойного приложения: D:\Apps\XB1ControllerBatteryIndicator\XB1ControllerBatteryIndicator.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 3360632a-3b85-42b0-8439-2949a936445e
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
I have the same issue that unknownsoldierx under nubmer 15

**Comment by NiyaShy** [comment]
Hey,
the error really looks similar to issue #15. As already mentioned in that issue, that message alone doesn't really say what is wrong.
Please check your event log for any additional log entries related to the crash.
Also, please check if your system is healthy. [this article](https://borncity.com/win/2016/07/08/check-and-repair-windows-system-files-and-component-store/) describes how to use SFC and DISM to check and (hopefully) repair your system.
