### ISSUE TITLE
Batteries "empty", controller still functions 2 hours later

### ISSUE THREAD

**Issue by davidponton** [NiyaShy/XB1ControllerBatteryIndicator#48]
I got the toast saying my controller's batteries were empty, but I ignored it. 2 hours of continuous use later, the controller still works. I feel like the empty warning should come a bit later than that? Or is this maybe just a problem specific to my batteries?

**Comment by NiyaShy** [comment]
Hey,
I have no influence on when the "empty" level is reached, that's determined by the driver or the controller itself. Most likely case is that the controller monitors the voltage the battery delivers and estimates its remaining charge by that. And the API used for polling the level knows no level below "empty". So it's probably that your batteries voltage drops below a certain threshold even though they still have enough charge left to keep the controller running.
