### ISSUE TITLE
Dissapear in tray after computer sleep or time

### ISSUE THREAD

**Issue by peterek1983** [NiyaShy/XB1ControllerBatteryIndicator#54]
I have a problem, XB1ControllerBatteryIndicator sometimes dissapear on tray. I can't right now exactly when this happen for 100% sure, but probably after computer sleep mode, and after that program process is shutdown by Windows 10.

How to run it to work everytime ?

**Comment by NiyaShy** [comment]
Hey,
sounds like the typical behaviour of windows to move "unused" systray icons into the overflow menu that you can reach via the little white arrow next to the visible icons. You can easily stop that by manually dragging the icon to any position in the visible icons, that way it should always get displayed and not move into the overflow any more.

**Comment by peterek1983** [comment]
Hey, no no this is not hidden, I have all systray icons option to be displayed in Win10.
Looks like program process after computer sleep is turn off. 
I check now, after wake up computer, icon is in tray, and when I move cursor on it imediatlly disappear..

**Comment by NiyaShy** [comment]
Hm... Thanks for testing, if it just "vanishes" it sounds like the process gets killed or crashes. Have you checked your event log if there are any entries about a crash?

**Comment by peterek1983** [comment]
Not yet, but thank you for hint, I must check this when will dissapear. 
btw. I use also reWASD program for controller which also have option to show battery status, maybe something here, one eat another :)

**Comment by peterek1983** [comment]
For now good no more dissapers!
I set on exe to run as Admin, maybe this helped, or maybe I run it before from shortcut, maybe something here cause problem.

**Comment by NiyaShy** [comment]
Great to hear that it stopped disappearing. Running it as admin shouldn't be necessary, but as long as it works that way...
