### ISSUE TITLE
Mouse and Keyboard Mode[Feature request]

### ISSUE THREAD

**Issue by RenanZX** [NiyaShy/XB1ControllerBatteryIndicator#60]
It would be nice if it had a mouse+keyboard mode like gopher project, to control mouse and keyboard in Windows, like xbox. You could swap mode to control PC again clicking start(menu button)+select(View Button).

**Comment by NiyaShy** [comment]
Do I understand you correctly that you want to emulate KB/M inputs via controller?
If so, there are probably already more than enough projects that can do that. I won't implement anything that goes that far beyond the main purpose, watching the battery level of your controller(s) and warning about low levels.

**Comment by RenanZX** [comment]
I only know about gopher, that don't have support anymore, DS4Windows only works on ps4 controllers, but it warns you from low battery levels, you can watch battery levels and you can set up some buttons to keyboard and mouse that is aweasome. I only suggest it, but if you think that it could be a bad idea, so it's fine.
