### ISSUE TITLE
[Feature Request] disable the notification entirely

### ISSUE THREAD

**Issue by doubledgedboard** [NiyaShy/XB1ControllerBatteryIndicator#64]
Hey I love this app, thanks so much for forking it and maintaining it.

For me, the "alert sound" feature is the ideal use case for me. I don't ever want any notification to pop-up because it could end up taking focus away from the game I'm in. The audio alert is enough for me.

So this is a feature request to consider allowing the ability to disable the pop-up alert.

**Comment by NiyaShy** [comment]
Hey, that's already implemented in what will become v1.4.0, see #55 for a "pre-release" with incomplete translations.
