### ISSUE TITLE
[Feature request] PS5

### ISSUE THREAD

**Issue by Trikos** [NiyaShy/XB1ControllerBatteryIndicator#65]
HI, the program is great, but it is possible to implement it also for a ps5 controller?
Thank you

**Comment by NiyaShy** [comment]
Hey,
in theory it would be possible, but AFAIK PS(5) controllers use bluetooth and a different "framework" for transmitting the button presses (aka, not XInput), and that would require implementing a completely different polling system just for that.

In short:
Possible: yes
Likely to happen: no

**Comment by Trikos** [comment]
Do you know if there something to check the battery level using code?

Il Mar 14 Giu 2022, 21:58 NiyaShy ***@***.***> ha scritto:

**Comment by NiyaShy** [comment]
Let me startpage that for you:
Found a reddit thread about monitoring the battery level of PS controllers, and according to it current versions of DS4Windows let you set up notifications and monitoring, including using the light bar and/or telling you on a button press. See https://www.reddit.com/r/PS5/comments/k3ekh5/dualsense_pc_battery_level/

**Comment by Trikos** [comment]
Awesome, thanks!

Il Mer 15 Giu 2022, 14:21 NiyaShy ***@***.***> ha scritto:
