### ISSUE TITLE
Controller connected via USB reported as "wired"

### ISSUE THREAD

**Issue by crxxzylol** [NiyaShy/XB1ControllerBatteryIndicator#66]
so basically when im opening the app and looking at the icon on the bar it says that the controller is wired  but its actually plugged in by the USB. Could you help me?

**Comment by NiyaShy** [comment]
Hey,
when you have it plugged into your computer via USB that is exactly the definition of the "wired" state, doesn't matter if the cable is hardwired or can be removed. If you just want to use USB for charging plug the cable into a power brick and not your computer so the controller connects via BT or microsofts proprietary protocol.

And just to mention it: that's not something I decided. The controller itself reports that it is in "wired" state and doesn't report any battery data then.
