### ISSUE TITLE
Hide Icon when there's no controller connected

### ISSUE THREAD

**Issue by Cupcake911** [NiyaShy/XB1ControllerBatteryIndicator#7]
Hi! Thanks for the little tool, it is very helpful.

I use my computer nearly 24/7, since I connect to it from everywhere to work via RDP. Obviously I have my controllers turned off when I'm not at home, so the icon shows no controller connected, which is correct.

Would it be possible to add the option of hiding the icon when there's no controller connected though?

Kindest regards.

**Comment by NiyaShy** [comment]
Hey,

it might be possible, there's just one issue with that: how do you want to interact with it when there is no icon? Also, I'm not really sure if a program that is only visible via a tray icon can disable/hide that icon.

**Comment by Shiyuri** [comment]
Can't think of any good solution for that, maybe opening the ".exe" file could enable the icon again for ~2 minutes?

If the program is unresponsive I can still close it via task manager but then again maybe not everyone may know how to use the task manager

**Comment by deefeloper** [comment]
I would suggest that there would be osd implemented, kinda like media player does

**Comment by LiamSho** [comment]
[Strings.zh.zip](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/files/3274489/Strings.zh.zip)

Hi, I translate in Chinese(S)

**Comment by NiyaShy** [comment]
To quickly summarize my stance on your suggestions:
* hide the main icon: nope, not even sure if it's possible and too high risk of inexperienced users "borking" it.
* multiple icons: nope, even more clutter...
* OSD: nay, too much hassle to implement and not that useful. The main focus of this program is to monitor the battery level and report low levels, nothing less, not much more.

As such, I'll take the liberty to close this issue.
