### ISSUE TITLE
Not executing after a Windows "repair".

### ISSUE THREAD

**Issue by Frankaupolis** [NiyaShy/XB1ControllerBatteryIndicator#74]
Hi, I've just made a "repair" of my Windows 10 using Microsoft's "Windows 10 installation media" creation tool. Since then only two issues have arisen, one of which is XB1ControllerBatteryIndicator not executing at all. I've tried running as admin but to no avail. I've tried both 1.2.1 and 1.3.1.1 versions. Anyone have an idea of what might be causing this?

Thanks in advance!

François

**Comment by Frankaupolis** [comment]
Hi NiyaShy, thanks for your response. "Have you checked event viewer..?": I'm not sure how to use this, I'm not at that level.. yet.. ;)
All I can see is, right after I launch the application, I see the app in Task Manager for 1 to 2 seconds before it disappears. I did just run the "sfc /scannow" command and it did find and fixed some errors. I then rebooted, but to no avail. Still the same behavior. Thanks for your help though. I will post here if anything changes.

**Comment by NiyaShy** [comment]
Hey,

for event viewer, do a right click on the "windows flag" button of your task bar, you should have an entry for it at the top of the menu. In there, expand "windows protocols" and open the "Application" log. (My system is in German, so the entries might be called slightly different)

When it crashes, you typically get 2 entries in the application log: one marked as an error, and one marked as information with the source "AppCrash". The content of both those entries can help to narrow down what's wrong.
