### ISSUE TITLE
Battery charge not showing

### ISSUE THREAD

**Issue by Dima-web-k** [NiyaShy/XB1ControllerBatteryIndicator#79]
When the gamepad is connected by wire, the program does not display the charge. Is it possible to somehow configure this, or maybe there is a version of the old version of the program that does not pay attention to this (I did not find one).
Sorry for my english, this is google translate

**Comment by NiyaShy** [comment]
Hey,
this behavior is normal because the controller does not report its battery level when it is connected to your computer via USB. Microsoft did it this way and I can't do anything about it.
