### ISSUE TITLE
Show battery level when connected via usb cable

### ISSUE THREAD

**Issue by dedo24397** [NiyaShy/XB1ControllerBatteryIndicator#8]
This feature would be useful for controllers with play&charge rechargable batteries. Indeed, one would know when the battery is fully charged

**Comment by Hp93** [comment]
Best regards,
Pham Hung.

________________________________

**Comment by NiyaShy** [comment]
That's (according to the official XInput documentation) not possible. as you can see [here](https://docs.microsoft.com/de-de/windows/desktop/api/xinput/ns-xinput-_xinput_battery_information) battery level is only reported for "wireless" controllers. I just tried it out by disabling the "wired" state check in the code, and an XBOne controller connected via USB always reported a full battery pack even though I put in one that was reported as medium on another controller.
