### ISSUE TITLE
Controller One found but still waiting for battery data

### ISSUE THREAD

**Issue by gdodd1977** [NiyaShy/XB1ControllerBatteryIndicator#81]
I have an Xbox Series X controller connected to my PC via USB-C cable. When I hover over the app icon in the tray it shows that it sees my controller but is waiting for battery data. My controllers use the official Xbox rechargeable batteries as well.

**Comment by NiyaShy** [comment]
Hey,
as long as you have the controller connected to your PC via USB, it should not report any battery data but instead show up as "wired". A bit weird that it stays at the "no data" stage, but that can sometimes happen.
 Weird thing is, I just tried it with my own Series X controller (model 1914), and when connected via USB it showed up with a battery state after a few seconds... "Wired" is only displayed when I remove the battery pack, so apparently Microsoft changed something with the newer controllers.

**Comment by Olanid57** [comment]
i have the same issue with my xbox controller via bluetooth @NiyaShy

**Comment by NiyaShy** [comment]
Can't be the same "issue" via BT. 
And since I haven't heard anything from OP for ~2 weeks i'll close this.
