### ISSUE TITLE
Charging indicator

### ISSUE THREAD

**Issue by Gamesiarz** [NiyaShy/XB1ControllerBatteryIndicator#86]
Could you please add indicator that detecting charging and fully charged status? On series s/x we don't have a orange/white led on cable.

**Comment by NiyaShy** [comment]
Hey,
sorry to say this, but I'm not sure if that's possible. The API that's used for getting the battery level has (AFAIK) no way of telling if the controller is being charged.

I will look into it, but the chances are rather slim that it will work.
