### ISSUE TITLE
Uninstalling Issue

### ISSUE THREAD

**Issue by Kerberos1864** [NiyaShy/XB1ControllerBatteryIndicator#88]
I can't uninstall this app anymore after installing it.
It appears in startup programs in task manager but can't be removed.
What is the proper way to uninstall ?
Thanks

**Comment by NiyaShy** [comment]
Hey, since there is no installer it's usually enough to just delete the exe file. If you want to remove the auto start entry beforehand, start it and disable automatic start via the context menu. Exit via context menu, delete .exe and the shortcut in the Windows start menu.

**Comment by saulob** [comment]
> Hey, since there is no installer it's usually enough to just delete the exe file. If you want to remove the auto start entry beforehand, start it and disable automatic start via the context menu. Exit via context menu, delete .exe and the shortcut in the Windows start menu.

1. Execute the program
2. Context menu in the taskbar (right mouse button)
3. Uncheck this option (_Start with Windows_)

![image](https://github.com/NiyaShy/XB1ControllerBatteryIndicator/assets/3660977/3ef60704-543e-4876-b6ad-141e142ad550)
