### ISSUE TITLE
Won't detect official xbox rechargable battery status in series x controller

### ISSUE THREAD

**Issue by dickyboy4444** [NiyaShy/XB1ControllerBatteryIndicator#94]
Windows 10

Xbox Series X controller

Via the 2.4ghz Microsoft Dongle

Been using this nice little app no issues with normal batteries.  Also works great with my 360 controllers.  Anyway I decided to buy a new official Microsoft rechargeable battery so I could recharge with USB C cable.  Now it wont detect the battery status.

**Comment by NiyaShy** [comment]
Hey,
does it not show the status at all or "just" when you have the controller plugged in for charging? And in the latter case: are you charging via a separate power brick or from a USB port on your device?

I have 2 official battery packs from the "play and charge" kits (model numbers 1556 and 1727, so most likely older revisions) and so far never had issues with them. Though I'm always charging them via a power brick and use my first broken xbone controller as a charging cradle.
