### ISSUE TITLE
Installation method using winget

### ISSUE THREAD

**Issue by comiluv** [NiyaShy/XB1ControllerBatteryIndicator#98]
Currently there's a [scoop package](https://scoop.sh/#/apps?q=xb1cbi) but AFAIK there's no winget package. I think it would be nice if there was a winget package too for easy installation and updates. Thank you.

**Comment by NiyaShy** [comment]
Never heard of scoop before, and I also don't know how it got listed there since I didn't do anything. So it either was some kind of automatism, or someone else added it there.

Concerning winget, I can look into how to publish something there, but I'll consider this a low priority.

**Comment by comiluv** [comment]
Closing the issue as stale for now, if anyone wants to reopen the issue please feel free to do so
